### ISSUE TITLE
Tailwind UI

### ISSUE THREAD

**Issue by cpwilson87** [cpwilson87/gitgud-svelteKit#10]
## Summary

Build a svelte component library using tailwind UI

### Phase 1 - Setup
- [x] Create SvelteKit Repo
- [x] Add Tailwind
- [x] Add Histoire
- [ ] Add Custom Palette
- [ ] Add Custom Font

## Phase 2 - Atoms

- [ ] Avatar
- [ ] Badge
- [ ] Button
- [ ] Button Group
- [ ] Modal
- [ ] Notification
- [ ] Dropdown

## References

- [Tailwind UI](https://tailwindui.com/)
- [Svelte Headless UI](https://svelte-headlessui.goss.io/docs/disclosure)
- [Flowbite Svelte](https://github.com/themesberg/flowbite-svelte/blob/main/src/lib/badges/Badge.svelte)
- [Temporal UI](https://github.com/temporalio/ui/blob/main/tailwind.config.cjs)
- [Tailwind Labs](https://www.youtube.com/@TailwindLabs/videos)
